# Generated by Django 3.2.9 on 2021-11-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('rating', models.PositiveBigIntegerField(default=0)),
                ('likes', models.PositiveBigIntegerField(default=0, null=True)),
                ('poster', models.ImageField(upload_to='pinterest_posters')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('rating', models.PositiveBigIntegerField(default=0)),
                ('likes', models.PositiveBigIntegerField(default=0, null=True)),
                ('poster', models.ImageField(upload_to='pinterest_posters')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
